Milestone 2 : User interface
enelesmai/tic-tac-toe pull request #4
Opened 2020-03-25 17:37 UTC by rubenpazch

+ Suggested branch name: user_interface.
+ main.rb file should be responsible for user interaction. In this milestone you should only create content in this file.
+ Think about steps needed to play the game:
+ what do you need from player?
+ what do you need to display for player?
+ Display prompts for users (hint: puts/print), collect user input (hint: get.chomp) and only mock the basic flow of the game (you can use puts or inline comments to say for example “Now, your move is displayed on the board”).
+ Make sure that you can run your game with your executable file and play with the basic flow.
+ The final point of this milestone is to make sure that you thought about all actions needed to play + Tic Tac Toe. It does not need to work yet - this will be done in the next milestone.

2020-03-25 18:24 UTC, shshamim63 requested changes

2020-03-25 18:24 UTC, shshamim63 commented on bin/main
> +puts "\n"
**Optional**
You can enclose it in a method. Cause every time it is not gonna be the same. something like.
```ruby
def display_board(board)
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts '---+---+---'
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts '---+---+---'
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
  puts "\n"
end
```

2020-03-25 18:44 UTC, shshamim63 requested changes
## Status :space_invader: Changes Required :space_invader: 
___
Hi @rubenpazch and @enelesmai :wave: 
Great initiative :clap: . You have covered almost all the messages. But have to cover some corner cases to get approval. And it is gonna be easy. 
___
### :spades: Mandatory Changes :spades: 
___
1. I can not see any message if a user inputs an invalid position or an occupied position.
2. You have provided a message to cover the winning case. But what about the draw? Please add a puts to cover this issue.
3.  A loop is needed in this game ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). Now the valid question I haven't started writing logic, So why I have to do so? Well In this milestone we are generating a scratch of this game. And from scratch, we can sense that some repetitive tasks is here that we need to cover. Just to make sure you have all cases on your hand before diving into game logic. For a suggestion, you can add,
```ruby
game_end = false

# initial instructions for player

until game_end
  # loop for each move
  
  if winner # and/or draw 
    game_end = true
  end
end
```
___
### :clubs: Optional Changes :clubs: 
___
1. You can enclose the puts that are generating boards output. You can check the comment :point_up_2: : 
___
#### After fixing all the issues please send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

2020-03-26 04:19 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-03-26 15:00 UTC, merged