Testing with rspec for project Tic-Tac-Toe
enelesmai/tic-tac-toe pull request #8
Opened 2020-03-31 21:48 UTC by rubenpazch

+ Add specs for all public methods you created in Tic Tac Toe project.
+ Use existing repositories for Tic Tac Toe and open new Pull Requests.
+ Create a feature branch for testing project 
+ Wrap specs for each method in describe block
+ Instead of using before_each to define a variable for the test cases, use let.
+ Use one it block for each expected behaviour. Do not test multiple aspects in one it block.
+ Use your common sense: test positive and negative scenarios.

2020-03-31 23:42 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
- [x] Lets write test for when there is a draw between both players

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-03-31 23:42 UTC, kobiyoyo commented on spec/board_spec.rb
> +require 'rspec'
You don't need this, lets remove this

2020-03-31 23:42 UTC, kobiyoyo commented on spec/game_spec.rb
> +require 'rspec'
You don't need this, lets remove this

2020-03-31 23:42 UTC, kobiyoyo commented on spec/player_list_spec.rb
> +require 'rspec'
You don't need this, lets remove this

2020-03-31 23:42 UTC, kobiyoyo commented on spec/player_spec.rb
> +require 'rspec'
You don't need this, lets remove this

2020-04-01 15:29 UTC, enelesmai commented on spec/game_spec.rb
> +require 'rspec'
Fixed, thanks for the suggestion!

2020-04-01 15:29 UTC, enelesmai commented on spec/player_list_spec.rb
> +require 'rspec'
Fixed, thanks for the suggestion!

2020-04-01 15:29 UTC, enelesmai commented on spec/player_spec.rb
> +require 'rspec'
Fixed, thanks for the suggestion!

2020-04-01 15:30 UTC, enelesmai commented on spec/board_spec.rb
> +require 'rspec'
Fixed, thanks for the suggestion!

2020-04-01 18:25 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap: 
### But kindly remove this file `rspec_results.html` its not needed for this project

2020-04-01 19:57 UTC, merged